### ISSUE TITLE
CONDA_PREFIX issue

### ISSUE THREAD

**Issue by Mehrnoosh-Moallemi** [PocketCoffea/PocketCoffea#110]
Hello, 
I am CMS PhD student testing PocketCoffea, and I was following the documentation in [PocketCoffea](https://pocketcoffea.readthedocs.io/en/latest/analysis_example.html) on lxplus, and after I created the singularity by:
```
apptainer shell --bind /afs -B /cvmfs/cms.cern.ch \
                --bind /tmp  --bind /eos/cms/ \
    --env KRB5CCNAME=$KRB5CCNAME --bind /etc/sysconfig/ngbauth-submit  \
    /cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-analysis/general/pocketcoffea:lxplus-cc7-latest
```
and clone with: git clone https://github.com/PocketCoffea/PocketCoffea.git and when I use 
```
runner.py --cfg example_config.py  --full --test -lf 1 -lc  2 -o output_v1
```
I have to mention that I was working with it last week and it worked completely, but this week 
for running it I constantly got this error:
```
File "/usr/local/bin/runner.py", line 146, in <module>
    f'conda activate {os.environ["CONDA_PREFIX"]}',
```
when we checked the runner file had been changed recently. ([link](https://github.com/PocketCoffea/PocketCoffea/commit/850fb031b023566aada5b2f190bb5596238a0fe4#diff-96cd37a272d0109b34069464280e60975deadb46f9949587e8d82a33e12e0f34L135))

**Comment by andreypz** [comment]
This is from my changes. I think it will work for you if you just move the `condor_extra = [ ]` block back under the `elif run_env == "conda"` block. So that it is not executed for you, since you do not use conda.

**Comment by valsdav** [comment]
@Mehrnoosh-Moallemi sorry for the inconvenience.  We are working on a refactoring of `runner.py` to avoid this kind of environment problems.

**Comment by Mehrnoosh-Moallemi** [comment]
Many thanks for fixing the issue.
