### ISSUE TITLE
Use sign(genWeight) instead of genWeight for MC scaling

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#130]
In current version of the Pocket, the MC scaling is done with `genWeight` variable. This is actually not recommended. Instead, one should use the `sign(genWeight)` and then `sum(sign(genWeight))` for the sum. 
This is mainly because there was a bug/feature of Run2 UL production when for some samples there are huge genWeights (which are incorrect). More details are in [this post on cms talk](https://cms-talk.web.cern.ch/t/huge-event-weights-in-dy-powhegminnlo/8718).
On the other hand some samples may require the actual value of the `genWeight` to be used, so  the framework should support both options.

Actually, I have implemented a solution. PR is coming shortly.

**Comment by valsdav** [comment]
Completed by #125
