### ISSUE TITLE
puId Bug in Jet_selection

### ISSUE THREAD

**Issue by Mehrnoosh-Moallemi** [PocketCoffea/PocketCoffea#133]
Hello,
I encountered a bug which is caused by the last update in [here](https://github.com/PocketCoffea/PocketCoffea/commit/e296c9e8540b090b07d950e7a442fd9707466325#diff-ec4cd240e3bb03845e50f08cb98756deb931e783df41665001ab72eebcf3cad7). So now when we use jet_selection for FatJets (Run 2 UL) it asks for FatJet.puId, which does not exist

**Comment by valsdav** [comment]
Hi I pushed a commit that should fix the issue. It will be in the singularity in ~30mins

**Comment by Mehrnoosh-Moallemi** [comment]
Many thanks.
