### ISSUE TITLE
Resolve wildcard options with click in merge_output.py script 

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#162]
We should have a way to resolve wildcards in options. Natively with `click` this is not supported (though with `argparse` it is, discuss in #153 ). At the end, this command should work:
`merge_outputs.py -i dir/output_*.coffea -o output_all.coffea`
With `click` one could write a method to catch these options and resolve, perhaps using `glob` to get list of files.

**Comment by andreypz** [comment]
I don't think the commit fixed the issue... Click still does not accept the wildcards, when there are more than one file in the list.

**Comment by valsdav** [comment]
Hi @andreypz. Can you have a look please at  [9605613](https://github.com/PocketCoffea/PocketCoffea/commit/9605613731248101fcfbed1a13bc8a0dc60cbb67)? 

The wildcard now works but the list of input files is taken as a positional argument, not as an option. 
It seems to work well.. Can you please try it out?

**Comment by andreypz** [comment]
Yes, I confirm this also works for me.
