### ISSUE TITLE
Too large empty margins on the plots

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#167]
It seems to me that  white spaces at the margins of the plots produced with the plotting script of pocket-coffea are too large. These may not be in agreement with the CMS style.
Compare [this plot form pocket-coffea example analysis](https://pocketcoffea.readthedocs.io/en/latest/_images/mll_2018_baseline.png)  and [this plot](https://cms-analysis.docs.cern.ch/guidelines/plotting/images/ex_labelout.png) from the CAT page.

There is also [tutorial from CAT](https://gitlab.cern.ch/cms-analysis/analysisexamples/plotting-demo/-/blob/master/2-tutorial_CAT_ratioplot.ipynb) with more plots (without large margin).

I looked a little into the plotting script, but I couldn't figure out where these margins are set. I may return to this later, but if someone else knows, please comment.

**Comment by valsdav** [comment]
I think this has been fixed by #178, right @felixzinn ?

**Comment by andreypz** [comment]
Indeed, it works for me. Closing.
