### ISSUE TITLE
Jet Enery Corrections are not applied to Data (but they should be)

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#177]
In the way JECs are implemented in PocketCoffea, they are only applied when `shape_variations` in the config are specified.
Moreover, those variations only seem to be applied to MC and [not to Data](https://github.com/PocketCoffea/PocketCoffea/blob/f7342feefd55697c5dc6551e9cd84726519841af/pocket_coffea/workflows/base.py#L602-L604). This makes sence for most correction but not JECs. The JECs should be applied to Data as well, [Ref](https://cms-jerc.web.cern.ch/JEC/).

For Run2 samples this is a minor issue since jets are already corrected in NanoAOD, but for Run3 this is a big issue, since in NanoAOD they jets seem to be way off the scale.
I haven't come up with a good way to implement the correction, thus making this issue for now.

**Comment by valsdav** [comment]
Thanks for the bringing this up @andreypz. Indeed for Run2 UL everything was applied, but now for Run3 we need to calibrate them.  Let me have a look at the code and we can discuss how to do it.

**Comment by valsdav** [comment]
Solved by #182
