### ISSUE TITLE
On the subsamples feature of the framework

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#180]
I've tested the `subsamples` functionality of the code. It works and it is great!
However, I have one suggestion. 
I think we should also fill and keep the histograms for the inclusive sample. At the moment, this is not the case (if I understood correctly), so only the subsamples are saved.
This is maybe OK if the subsamples actually sum up to the inclusive sample, but this may not be the case. There is nothing in the code  that ensures this. So, it  would be useful to also keep the inclusive histogram even when subsamples are used. Then it can be disabled/enabled in plotting via `exclude_samples` option.

Not sure how to do this. so just creating an issue for now.

**Comment by valsdav** [comment]
Hi @andreypz. 
One possibility, that would not require to modify the core workflow for subsamples, is to define an "inclusive" subsample with the "passthrough" (all-True) cut. 

I think this would be clear enough for the user and would not require ad hoc changes for this behavior.   Do you think it is meaningful enough to define it like this?

**Comment by andreypz** [comment]
Thanks, this is Indeed a working solution, and an obvious one. Should have thought of that myself...
It solves it for me, so closing the issue.
