### ISSUE TITLE
Electron Trigger Scale Factors: Wrong arguments passed to get electron trigger scale factors

### ISSUE THREAD

**Issue by felixzinn** [PocketCoffea/PocketCoffea#198]
The function [`get_ele_sf`](https://github.com/PocketCoffea/PocketCoffea/blob/main/pocket_coffea/lib/scale_factors.py#L6-L8) was updated to include 2023 Electron SF, which required an additional argument `phi`.

The function [`sf_ele_trigger`](https://github.com/PocketCoffea/PocketCoffea/blob/main/pocket_coffea/lib/scale_factors.py#L224-L232) is not updated to also pass `phi` as an argument and hence fails, because `ele_counts` gets passed to `phi` and `'trigger'` gets passed to `counts`.

```python
def get_ele_sf(
        params, year, pt, eta, phi, counts=None, key='', pt_region=None, variations=["nominal"]
):
  ...

def sf_ele_trigger(params, events, year, variations=["nominal"]):
  sf_dict = get_ele_sf(
    params,
    year,
    ele_pt_flat,
    ele_eta_flat,
    ele_counts,
    'trigger',
    variations=variations,
  )
  ```

**Comment by valsdav** [comment]
Hi, Thanks for opening the issue. 

I have fixed this in the upcoming PR with the Weights improvement :+1:
