### ISSUE TITLE
2016 year naming consistency

### ISSUE THREAD

**Issue by valsdav** [PocketCoffea/PocketCoffea#33]
The 2016 datataking period is identified in the framework by two different year labels: `2016preVFP` and `2016postVFP`. 
We must be consistent with this naming in all the parameters:  we need to choose between `2016preVFP` and `2016_PreVFP`

- https://github.com/PocketCoffea/PocketCoffea/blob/34bb797feb07bf5718622371d5228a56a9da4da4/PocketCoffea/parameters/pileup.py#L2
- https://github.com/PocketCoffea/PocketCoffea/blob/34bb797feb07bf5718622371d5228a56a9da4da4/PocketCoffea/parameters/jec.py#L2
- https://github.com/PocketCoffea/PocketCoffea/blob/34bb797feb07bf5718622371d5228a56a9da4da4/PocketCoffea/parameters/lepton_scale_factors.py#L10

**Comment by mmarchegiani** [comment]
The scheme `2016_PreVFP` and `2016_PostVFP` has been chosen as default.
