### ISSUE TITLE
Plotting script crashing when trying to create output directories with multiprocessing

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#93]
Running the example analysis config I notice a crash that (sometimes) happens when running the `make_plots.py` script with new output directory and using `-j N` option. I think the issues is in `os.makedirs()` function: https://github.com/PocketCoffea/PocketCoffea/blob/main/pocket_coffea/utils/plot_utils.py#L622
When multiple processes trying to create the same directory it crashes. Running the script second time overcomes the problem.

Conceptually the solution is easy. Either need to create all the directories before launching multiprocessing pool, or using Lock method from multiprocessing. However, I was not able to fix it myself yet. Maybe can do it later, if no one else does it first.

**Comment by mmarchegiani** [comment]
Solved by PR #98.
